/*
===========================================================================
The Nomad AGPL Source Code
Copyright (C) 2025 Noah Van Til

The Nomad Source Code is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

The Nomad Source Code is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with The Nomad Source Code.  If not, see <http://www.gnu.org/licenses/>.

If you have questions concerning this license or the applicable additional
terms, you may contact me via email at nyvantil@gmail.com.
===========================================================================
*/

using NomadCore.Abstractions.Services;
using NomadCore.Infrastructure;
using NomadCore.Interfaces.ConsoleSystem;
using System;
using System.Collections.Generic;

namespace NomadCore.Systems.ConsoleSystem.CVars.Infrastructure {
	/*
	===================================================================================
	
	ConfigFileWriter
	
	===================================================================================
	*/
	/// <summary>
	/// Writes CVars and CVarGroups to a configuration file, specifically in .ini format.
	/// </summary>

	internal readonly ref struct ConfigFileWriter {
		private readonly System.IO.StreamWriter Writer;
		private readonly ICVarSystemService CVarSystem;

		/*
		===============
		ConfigFileWriter
		===============
		*/
		/// <summary>
		/// 
		/// </summary>
		/// <param name="configFile"></param>
		/// <param name="groups"></param>
		public ConfigFileWriter( string? configFile, in HashSet<CVarGroup>? groups ) {
			ArgumentException.ThrowIfNullOrEmpty( configFile );
			ArgumentNullException.ThrowIfNull( groups );

			var logger = ServiceRegistry.Get<ILoggerService>();

			if ( groups.Count <= 0 ) {
				logger?.PrintWarning( "ConfigFileWriter: no CVar groups provided" );
				return;
			}

			CVarSystem = ServiceRegistry.Get<ICVarSystemService>();

			try {
				string? directory = System.IO.Path.GetDirectoryName( configFile );
				if ( !string.IsNullOrEmpty( directory ) && !System.IO.Directory.Exists( directory ) ) {
					System.IO.Directory.CreateDirectory( directory );
				}

				using System.IO.FileStream? fileStream = new System.IO.FileStream( configFile, System.IO.FileMode.Create, System.IO.FileAccess.Write );
				using ( Writer = new System.IO.StreamWriter( fileStream ) ) {
					WriteHeader();

					foreach ( var group in groups ) {
						WriteGroup( group );
					}
				}
			} catch ( Exception e ) {
				Writer?.Close();
				logger?.PrintError( $"...Error writing configuration file {configFile}: {e.Message}" );
			}
		}

		/*
		===============
		WriteHeader
		===============
		*/
		/// <summary>
		/// 
		/// </summary>
		private void WriteHeader() {
			Writer.WriteLine( "; ===========================================================================" );
			Writer.WriteLine( "; Configuration File - Auto-generated by NomadCore CVarSystem" );
			Writer.WriteLine( $"; Generated on: {DateTime.Now:yyyy-MM-dd HH:mm:ss}" );
			Writer.WriteLine( "; ===========================================================================" );
			Writer.WriteLine();
		}

		/*
		===============
		WriteVariable
		===============
		*/
		/// <summary>
		/// Writes a cvar's value to the configuration file
		/// </summary>
		/// <param name="cvar">The cvar to serialize</param>
		public readonly void WriteVariable( in ICVar? cvar ) {
			ArgumentNullException.ThrowIfNull( cvar );

			Writer.WriteLine( $"{cvar.Name}={cvar.GetStringValue()}" );
		}

		/*
		===============
		WriteGroup
		===============
		*/
		/// <summary>
		/// 
		/// </summary>
		/// <param name="group"></param>
		private void WriteGroup( in CVarGroup group ) {
			ArgumentNullException.ThrowIfNull( group );

			if ( group.Cvars.Count == 0 ) {
				return;
			}

			Writer.WriteLine();
			if ( !string.IsNullOrEmpty( group.Name ) ) {
				Writer.WriteLine( $"[{group.Name}]" );
				Writer.WriteLine( $"; {group.Name} settings" );
			} else {
				Writer.WriteLine( "[General]" );
				Writer.WriteLine( "; General settings" );
			}
			Writer.WriteLine();

			foreach ( var cvar in group.Cvars ) {
				WriteVariable( CVarSystem.GetCVar( cvar ) );
			}
		}
	};
};