/*
===========================================================================
The Nomad Framework
Copyright (C) 2025-2026 Noah Van Til

This Source Code Form is subject to the terms of the Mozilla Public
License, v2. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/.

This software is provided "as is", without warranty of any kind,
express or implied, including but not limited to the warranties
of merchantability, fitness for a particular purpose and noninfringement.
===========================================================================
*/

using System;
using System.Collections.Generic;
using Nomad.Core.Logger;

namespace Nomad.CVars.Private.Repositories {
	/*
	===================================================================================

	ConfigFileWriter

	===================================================================================
	*/
	/// <summary>
	/// Writes CVars and CVarGroups to a configuration file, specifically in .ini format.
	/// </summary>

	internal readonly ref struct ConfigFileWriter {
		private readonly System.IO.StreamWriter _writer;
		private readonly ICVarSystemService _cvarSystem;

		/*
		===============
		ConfigFileWriter
		===============
		*/
		/// <summary>
		///
		/// </summary>
		/// <param name="configFile"></param>
		/// <param name="logger"></param>
		/// <param name="cvarSystem"></param>
		/// <param name="groups"></param>
		public ConfigFileWriter( string configFile, ILoggerService logger, ICVarSystemService cvarSystem, in IEnumerable<ICVar> cvars ) {
			ArgumentException.ThrowIfNullOrEmpty( configFile );

			_cvarSystem = cvarSystem;
			logger.PrintLine( $"ConfigFileWriter: writing cvar config...." );

			try {
				string? directory = System.IO.Path.GetDirectoryName( configFile );
				if ( !string.IsNullOrEmpty( directory ) && !System.IO.Directory.Exists( directory ) ) {
					System.IO.Directory.CreateDirectory( directory );
				}

				using System.IO.FileStream? fileStream = new System.IO.FileStream( configFile, System.IO.FileMode.Create, System.IO.FileAccess.Write );
				using ( _writer = new System.IO.StreamWriter( fileStream ) ) {
					WriteHeader();
					foreach ( var cvar in cvars ) {
						WriteVariable( in cvar );
					}
					_writer.Flush();
				}
			} catch ( Exception e ) {
				_writer?.Close();
				logger.PrintError( $"...Error writing configuration file {configFile}: {e.Message}" );
				throw;
			}
		}

		/*
		===============
		WriteHeader
		===============
		*/
		/// <summary>
		///
		/// </summary>
		private void WriteHeader() {
			_writer.WriteLine( "; ===========================================================================" );
			_writer.WriteLine( "; Configuration File - Auto-generated by NomadCore CVarSystem" );
			_writer.WriteLine( $"; Generated on: {DateTime.Now:yyyy-MM-dd HH:mm:ss}" );
			_writer.WriteLine( "; ===========================================================================" );
			_writer.WriteLine();
		}

		/*
		===============
		WriteVariable
		===============
		*/
		/// <summary>
		/// Writes a cvar's value to the configuration file
		/// </summary>
		/// <param name="cvar">The cvar to serialize</param>
		public readonly void WriteVariable( in ICVar? cvar ) {
			ArgumentNullException.ThrowIfNull( cvar );

			switch ( cvar.Type ) {
				case CVarType.Boolean:
					_writer.WriteLine( $"{cvar.Name}={cvar.GetBooleanValue()}" );
					break;
				case CVarType.Int:
					_writer.WriteLine( $"{cvar.Name}={cvar.GetIntegerValue()}" );
					break;
				case CVarType.UInt:
					_writer.WriteLine( $"{cvar.Name}={cvar.GetUIntegerValue()}" );
					break;
				case CVarType.String:
					_writer.WriteLine( $"{cvar.Name}={cvar.GetStringValue()}" );
					break;
				case CVarType.Decimal:
					_writer.WriteLine( $"{cvar.Name}={cvar.GetDecimalValue()}" );
					break;
			}
		}

		/*
		===============
		WriteGroup
		===============
		*/
		/// <summary>
		///
		/// </summary>
		/// <param name="group"></param>
		private void WriteGroup( in CVarGroup group ) {
			ArgumentNullException.ThrowIfNull( group );

			if ( group.Cvars.Count == 0 ) {
				return;
			}

			_writer.WriteLine();
			if ( !string.IsNullOrEmpty( group.Name ) ) {
				_writer.WriteLine( $"[{group.Name}]" );
				_writer.WriteLine( $"; {group.Name} settings" );
			} else {
				_writer.WriteLine( "[General]" );
				_writer.WriteLine( "; General settings" );
			}
			_writer.WriteLine();

			foreach ( var cvar in group.Cvars ) {
				WriteVariable( _cvarSystem.GetCVar( cvar ) );
			}
		}
	};
};
