/*
===========================================================================
The Nomad Framework
Copyright (C) 2025-2026 Noah Van Til

This Source Code Form is subject to the terms of the Mozilla Public
License, v2. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/.

This software is provided "as is", without warranty of any kind,
express or implied, including but not limited to the warranties
of merchantability, fitness for a particular purpose and noninfringement.
===========================================================================
*/

using System;
using System.Collections.Generic;
using System.IO;
using Nomad.Core.Compatibility.Guards;
using Nomad.Core.CVars;
using Nomad.Core.FileSystem;
using Nomad.Core.FileSystem.Configs;
using Nomad.Core.FileSystem.Streams;
using Nomad.Core.Logger;
using Nomad.CVars.Private.Entities;

namespace Nomad.CVars.Private.Serialization {
	/*
	===================================================================================

	ConfigFileWriter

	===================================================================================
	*/
	/// <summary>
	/// Writes CVars and CVarGroups to a configuration file, specifically in .ini format.
	/// </summary>

	internal readonly ref struct ConfigFileWriter {
		private readonly IFileWriteStream? _writer;
		private readonly ICVarSystemService _cvarSystem;

		/*
		===============
		ConfigFileWriter
		===============
		*/
		/// <summary>
		/// 
		/// </summary>
		/// <param name="configFile"></param>
		/// <param name="logger"></param>
		/// <param name="cvarSystem"></param>
		/// <param name="fileSystem"></param>
		/// <param name="groups"></param>
		public ConfigFileWriter( string configFile, ILoggerService logger, ICVarSystemService cvarSystem, IFileSystem fileSystem, ICollection<CVarGroup> groups ) {
			ArgumentGuard.ThrowIfNullOrEmpty( configFile );

			_cvarSystem = cvarSystem;
			logger.PrintLine( $"ConfigFileWriter: writing cvar config to {configFile}...." );

			_writer = null;

			try {
				string? directoryPath = Path.GetDirectoryName( configFile );
				if ( !string.IsNullOrWhiteSpace( directoryPath ) && !fileSystem.DirectoryExists( directoryPath ) ) {
					fileSystem.CreateDirectory( directoryPath );
				}

				using ( _writer = fileSystem.OpenWrite( new FileWriteConfig { FilePath = configFile, Format = StreamFormat.Utf8 } ) as IFileWriteStream ) {
					WriteHeader();
					foreach ( var group in groups ) {
						WriteGroup( group );
					}
					_writer.Flush();
				}
			} catch ( Exception e ) {
				_writer?.Close();
				logger.PrintError( $"...Error writing configuration file {configFile}: {e.Message}" );
				throw;
			}
		}

		/*
		===============
		WriteHeader
		===============
		*/
		/// <summary>
		///
		/// </summary>
		private void WriteHeader() {
			_writer.WriteLine( "; ===========================================================================" );
			_writer.WriteLine( "; Configuration File - Auto-generated by Nomad.CVars System" );
			_writer.WriteLine( $"; Generated on: {DateTime.Now:yyyy-MM-dd HH:mm:ss}" );
			_writer.WriteLine( "; ===========================================================================" );
			_writer.WriteLine( string.Empty );
		}

		/*
		===============
		WriteVariable
		===============
		*/
		/// <summary>
		/// Writes a cvar's value to the configuration file
		/// </summary>
		/// <param name="cvar">The cvar to serialize</param>
		private readonly void WriteVariable( ICVar cvar ) {
			ArgumentGuard.ThrowIfNull( cvar );
			switch ( cvar.Type ) {
				case CVarType.Boolean:
					_writer.WriteLine( $"{cvar.Name}={cvar.GetBooleanValue()}" );
					break;
				case CVarType.Int:
					_writer.WriteLine( $"{cvar.Name}={cvar.GetIntegerValue()}" );
					break;
				case CVarType.UInt:
					_writer.WriteLine( $"{cvar.Name}={cvar.GetUIntegerValue()}" );
					break;
				case CVarType.String:
					_writer.WriteLine( $"{cvar.Name}=\"{cvar.GetStringValue()}\"" );
					break;
				case CVarType.Decimal:
					_writer.WriteLine( $"{cvar.Name}={cvar.GetDecimalValue()}" );
					break;
			}
		}

		/*
		===============
		WriteGroup
		===============
		*/
		/// <summary>
		///
		/// </summary>
		/// <param name="group"></param>
		private void WriteGroup( ICVarGroup group ) {
			ArgumentGuard.ThrowIfNull( group );

			_writer.WriteLine( string.Empty );
			_writer.WriteLine( $"[{group.Name}]" );

			foreach ( var cvar in group.CVars ) {
				WriteVariable( _cvarSystem.GetCVar( cvar.Name ) );
			}
		}
	};
};
